-- create a new table that stores the pokemon type to its corresponding against_x columns
-- all the against_x columns depends on the primary key(pokemon_type)
CREATE TABLE if not EXISTS type_against (
  pokemon_type STRING PRIMARY KEY, 
  against_bug FLOAT,
  against_dark FLOAT,
  against_dragon FLOAT,
  against_electric FLOAT,
  against_fairy FLOAT,
  against_fight FLOAT,
  against_fire FLOAT,
  against_flying FLOAT,
  against_ghost FLOAT,
  against_grass FLOAT,
  against_ground FLOAT,
  against_ice FLOAT,
  against_normal FLOAT,
  against_poison FLOAT,
  against_psychic FLOAT,
  against_rock FLOAT,
  against_steel FLOAT,
  against_water FLOAT
);

--select and insert the columns from imported_pokemon_data table into type_against table 
--the condition of select is the pokemon with 2 types and pokemon with type1 and type2 is null. 
INSERT INTO  type_against
SELECT * FROM (select case when type2 is not null then type1||'&'||type2 else type1 end  AS pokemon_type,
against_bug,
against_dark,
against_dragon,
against_electric,
against_fairy,
against_fight,
against_fire,
against_flying,
against_ghost,
against_grass,
against_ground,
against_ice,
against_normal,
against_poison,
against_psychic,
against_rock,
against_steel,
against_water
FROM imported_pokemon_data) GROUP BY pokemon_type,
against_bug,
against_dark,
against_dragon,
against_electric,
against_fairy,
against_fight,
against_fire,
against_flying,
against_ghost,
against_grass,
against_ground,
against_ice,
against_normal,
against_poison,
against_psychic,
against_rock,
against_steel,
against_water;
